/**
 * CromIam
 * Cromwell's Bouncer
 *
 * OpenAPI spec version: 
 * Contact: dsde@broadinstitute.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package woodard.model

import java.util.Date

case class WorkflowQueryResult (
  // Workflow ID
  id: String,
  // Workflow name
  name: String,
  // Workflow status
  status: String,
  // Workflow start datetime
  start: Date,
  // Workflow end datetime
  end: Option[Date] = None
)

