/**
 * CromIam
 * Cromwell's Bouncer
 *
 * OpenAPI spec version: 
 * Contact: dsde@broadinstitute.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package woodard.model

import java.util.Date

case class FailureMessage (
  // The failure message
  failure: String,
  // The time at which this failure occurred
  timestamp: Date
)

