/**
 * CromIam
 * Cromwell's Bouncer
 *
 * OpenAPI spec version: 
 * Contact: dsde@broadinstitute.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package woodard.model


case class StatusResponse (
  serviceName: Option[StatusResponseServiceName] = None
)

